import { Cable, Eye, EyeOff, FolderKanban, KeyRound, MousePointer2, Settings2, ShieldCheck, Sparkles, Trash2 } from 'lucide-react'
import type { FormEvent } from 'react'
import type { AgentGraphMode } from '../core/agentic-graph'
import { AgentChoiceCard } from './AgentChoiceCard'
import { ChatGPTAccountSettings } from './ChatGPTAccountSettings'

export function AgentSettingsContent({ apiKey, autoApply, chatGPT, confirmDelete, credentialBusy, credentialMessage, graphMode, loading, onApiKeyChange, onAutoApplyChange, onChatGPTConfigurationChange, onConnectChatGPT, onDeleteApiKey, onDisconnectChatGPT, onGraphModeChange, onSaveApiKey, onShowApiKeyChange, onTestApiKey, settings, showApiKey }: { apiKey: string; autoApply: boolean; chatGPT?: ChatGPTSessionStatus; confirmDelete: boolean; credentialBusy: boolean; credentialMessage: string; graphMode: AgentGraphMode; loading: boolean; onApiKeyChange(value: string): void; onAutoApplyChange(value: boolean): void; onChatGPTConfigurationChange(configuration: { model: string; effort: string }): void; onConnectChatGPT(): void; onDeleteApiKey(): void; onDisconnectChatGPT(): void; onGraphModeChange(value: AgentGraphMode): void; onSaveApiKey(event: FormEvent): void; onShowApiKeyChange(value: boolean): void; onTestApiKey(): void; settings?: OpenAISettingsStatus; showApiKey: boolean }) {
  return <div className="ask-labo-settings-content">
    <div className="ask-labo-intro"><strong>Atomic graph agent</strong><p>LABO inspects the typed card library, composes missing reusable cards when possible, wires the graph and returns an explicit plan.</p></div>
    <AgentChoiceCard ariaLabel="Agent apply mode" description={autoApply ? 'Apply every locally valid operation immediately.' : 'Preview cards and elastics before applying.'} label="Approval">
      <button aria-pressed={!autoApply} onClick={() => onAutoApplyChange(false)} type="button">Review</button><button aria-pressed={autoApply} onClick={() => onAutoApplyChange(true)} type="button">Auto apply</button>
    </AgentChoiceCard>
    <AgentChoiceCard ariaLabel="Agent graph scope" description={graphMode === 'parallel' ? 'Keep the existing graph read-only and build beside it.' : 'Connect new cards to compatible free ports.'} label="Graph scope">
      <button aria-pressed={graphMode === 'extend'} disabled={loading} onClick={() => onGraphModeChange('extend')} type="button">Extend current</button><button aria-pressed={graphMode === 'parallel'} disabled={loading} onClick={() => onGraphModeChange('parallel')} type="button">New parallel</button>
    </AgentChoiceCard>
    {window.labo?.runtime === 'electron' && <ChatGPTAccountSettings busy={credentialBusy} onConfigurationChange={onChatGPTConfigurationChange} onConnect={onConnectChatGPT} onDisconnect={onDisconnectChatGPT} session={chatGPT} />}
    <section className="ask-labo-key-settings">
      <div className="ask-labo-key-heading"><span><KeyRound size={13} />{window.labo?.runtime === 'electron' ? 'OpenAI API key · optional fallback' : 'OpenAI API key'}</span>{settings?.configured && <b><span className="status-dot" />Connected</b>}</div>
      {settings?.configured ? <><div className="ask-labo-key-status"><ShieldCheck size={16} /><span><strong>{settings.source === 'secure-storage' ? 'Stored securely for this user' : 'Provided by the app environment'}</strong><small>Secure storage is opened only when this provider is actually used.</small></span></div><div className="ask-labo-key-actions"><button disabled={credentialBusy} onClick={onTestApiKey} type="button">Test connection</button>{settings.source === 'secure-storage' && <button className={confirmDelete ? 'confirm-delete' : ''} disabled={credentialBusy} onClick={onDeleteApiKey} type="button"><Trash2 size={12} />{confirmDelete ? 'Confirm removal' : 'Remove key'}</button>}{window.labo?.runtime === 'web' && <a href="/dashboard/settings" target="_top">Manage account</a>}</div></> : settings?.authRequired ? <div className="ask-labo-key-form"><p>Everything except Ask LABO works without an account.</p><a className="ask-labo-sign-in" href="/auth/signin?callbackUrl=%2Flabo-ai%2Flive" target="_top"><ShieldCheck size={12} />Sign in to use the agent</a></div> : <form className="ask-labo-key-form" onSubmit={onSaveApiKey}><p>No API key configured for this user.</p><small>Disabled by default. The system keychain is contacted only after you submit a key here.</small><label htmlFor="openai-api-key">OpenAI API key</label><div><input autoComplete="off" id="openai-api-key" onChange={(event) => onApiKeyChange(event.target.value)} placeholder="sk-…" type={showApiKey ? 'text' : 'password'} value={apiKey} /><button aria-label={showApiKey ? 'Hide API key' : 'Show API key'} onClick={() => onShowApiKeyChange(!showApiKey)} type="button">{showApiKey ? <EyeOff size={13} /> : <Eye size={13} />}</button></div><button disabled={credentialBusy || apiKey.trim().length < 20 || settings?.encryptionAvailable === false} type="submit"><ShieldCheck size={12} />{credentialBusy ? 'Saving…' : 'Save and verify key'}</button>{settings?.encryptionAvailable === false && <small>Secure storage requires the LABO AI desktop app and an available system keychain.</small>}</form>}
      {credentialMessage && <p className="ask-labo-key-message">{credentialMessage}</p>}
    </section>
  </div>
}

export function StudioEditingTips() {
  return <div className="ask-labo-tips">
    <article><span><MousePointer2 size={14} />Select & delete</span><strong>Delete several cards or a full graph</strong><p>Switch to <b>Edit cards</b>, then drag on empty canvas around the cards. Hold Shift, Cmd or Ctrl while clicking to adjust the selection, then choose <b>Delete selection</b>. Connected elastics are removed with the cards.</p></article>
    <article><span><Settings2 size={14} />Edit a card</span><strong>Open card settings</strong><p>In <b>Edit cards</b>, click a card to open its settings. You can also right-click a card for the Edit and Delete actions.</p></article>
    <article><span><Cable size={14} />Add & wire</span><strong>Compose manually</strong><p>Use <b>Add blocks</b>, click a card to place it automatically or drag it onto the canvas, then drag between compatible typed plugs.</p></article>
    <article><span><FolderKanban size={14} />Save & compare</span><strong>Keep each architecture reusable</strong><p>Open <b>Settings → Workspaces</b> to name, save, reset or place complete presets side by side.</p></article>
    <article><span><Sparkles size={14} />Ask LABO</span><strong>Build with natural language</strong><p>Describe the architecture in the footer prompt. Configure review, auto-apply and parallel mode under <b>Settings → Agent</b>.</p></article>
    <article><span><ShieldCheck size={14} />Desktop sign-in</span><strong>Use your ChatGPT account without an API key</strong><p>In the desktop app, open <b>Settings → Agent</b> and connect ChatGPT. The API-key field remains an optional fallback and is not required for this mode.</p></article>
  </div>
}
