import type { ArchitectureGraph } from './ir'

export const blankStarterPreset: ArchitectureGraph = {
  id: 'blank-starter',
  name: 'Blank starter',
  architecture: 'custom',
  config: { hiddenSize: 768, queryHeads: 12, keyValueHeads: 4, headDim: 64 },
  contracts: { causal: false, preservesGqaAtZeroGate: false, sdpaCompatible: false, contextualValue: false },
  nodes: [],
  edges: [],
}

export const gptLikeStarterPreset: ArchitectureGraph = {
  id: 'gpt-like-starter',
  name: 'GPT-like Starter',
  architecture: 'custom',
  config: { hiddenSize: 768, queryHeads: 12, keyValueHeads: 12, headDim: 64 },
  contracts: { causal: true, preservesGqaAtZeroGate: false, sdpaCompatible: true, contextualValue: true },
  nodes: [
    { id: 'tokens', kind: 'input', label: 'Token IDs', role: 'token-ids', position: { x: 190, y: 35 } },
    { id: 'embedding', kind: 'semantic', atomId: 'token-embedding', label: 'Tied token embedding', role: 'hidden', position: { x: 190, y: 145 }, attributes: { vocabSize: 32000, hiddenSize: 768 } },
    { id: 'attention-norm', kind: 'semantic', atomId: 'rms-norm', label: 'Attention RMSNorm', role: 'hidden', position: { x: 190, y: 255 }, attributes: { epsilon: 1e-6 } },
    { id: 'qkv', kind: 'semantic', atomId: 'qkv-projection', label: '12-head QKV projection', role: 'output', position: { x: 190, y: 365 }, attributes: { bias: false, fused: true } },
    { id: 'head-layout', kind: 'semantic', atomId: 'attention-head-layout', label: '12 Q / 12 KV heads', role: 'output', position: { x: 190, y: 485 }, attributes: { queryHeads: 12, keyValueHeads: 12, headDim: 64 } },
    { id: 'rope', kind: 'semantic', atomId: 'rope', label: 'RoPE position encoding', role: 'output', position: { x: 70, y: 605 }, attributes: { base: 10000 } },
    { id: 'sdpa', kind: 'semantic', atomId: 'causal-sdpa', label: 'Causal self-attention', role: 'attention', position: { x: 190, y: 725 }, attributes: { dropout: 0 } },
    { id: 'merge-heads', kind: 'semantic', atomId: 'merge-attention-heads', label: 'Merge attention heads', role: 'hidden', position: { x: 190, y: 835 } },
    { id: 'attention-output', kind: 'semantic', atomId: 'attention-output-projection', label: 'Attention output projection', role: 'hidden', position: { x: 190, y: 945 }, attributes: { bias: false } },
    { id: 'attention-residual', kind: 'semantic', atomId: 'residual-add', label: 'Attention residual add', role: 'hidden', position: { x: 190, y: 1055 } },
    { id: 'mlp-norm', kind: 'semantic', atomId: 'rms-norm', label: 'MLP RMSNorm', role: 'hidden', position: { x: 190, y: 1165 }, attributes: { epsilon: 1e-6 } },
    { id: 'mlp', kind: 'semantic', atomId: 'swiglu-mlp', label: 'Dense SwiGLU MLP', role: 'hidden', position: { x: 190, y: 1275 }, attributes: { intermediateSize: 3072, bias: false } },
    { id: 'mlp-residual', kind: 'semantic', atomId: 'residual-add', label: 'MLP residual add', role: 'hidden', position: { x: 190, y: 1385 } },
    { id: 'final-norm', kind: 'semantic', atomId: 'rms-norm', label: 'Final RMSNorm', role: 'hidden', position: { x: 190, y: 1495 }, attributes: { epsilon: 1e-6 } },
    { id: 'head', kind: 'semantic', atomId: 'lm-head', label: 'Tied language-model head', role: 'output', position: { x: 190, y: 1605 }, attributes: { vocabSize: 32000, tieEmbeddingWeights: true, bias: false } },
  ],
  edges: [
    { id: 'tokens-embedding', source: 'tokens', sourcePort: 'tokenIds', target: 'embedding', targetPort: 'tokenIds' },
    { id: 'embedding-attention-norm', source: 'embedding', sourcePort: 'output', target: 'attention-norm', targetPort: 'hidden' },
    { id: 'attention-norm-qkv', source: 'attention-norm', sourcePort: 'output', target: 'qkv', targetPort: 'hidden' },
    { id: 'qkv-q-layout', source: 'qkv', sourcePort: 'q', target: 'head-layout', targetPort: 'q' },
    { id: 'qkv-k-layout', source: 'qkv', sourcePort: 'k', target: 'head-layout', targetPort: 'k' },
    { id: 'qkv-v-layout', source: 'qkv', sourcePort: 'v', target: 'head-layout', targetPort: 'v' },
    { id: 'layout-q-rope', source: 'head-layout', sourcePort: 'qHeads', target: 'rope', targetPort: 'q' },
    { id: 'layout-k-rope', source: 'head-layout', sourcePort: 'kHeads', target: 'rope', targetPort: 'k' },
    { id: 'rope-q-sdpa', source: 'rope', sourcePort: 'q', target: 'sdpa', targetPort: 'q' },
    { id: 'rope-k-sdpa', source: 'rope', sourcePort: 'k', target: 'sdpa', targetPort: 'k' },
    { id: 'layout-v-sdpa', source: 'head-layout', sourcePort: 'vHeads', target: 'sdpa', targetPort: 'v' },
    { id: 'sdpa-merge-heads', source: 'sdpa', sourcePort: 'output', target: 'merge-heads', targetPort: 'attention' },
    { id: 'merge-heads-output', source: 'merge-heads', sourcePort: 'output', target: 'attention-output', targetPort: 'hidden' },
    { id: 'embedding-attention-residual', source: 'embedding', sourcePort: 'output', target: 'attention-residual', targetPort: 'residual' },
    { id: 'attention-output-residual', source: 'attention-output', sourcePort: 'output', target: 'attention-residual', targetPort: 'branch' },
    { id: 'attention-residual-mlp-norm', source: 'attention-residual', sourcePort: 'output', target: 'mlp-norm', targetPort: 'hidden' },
    { id: 'mlp-norm-mlp', source: 'mlp-norm', sourcePort: 'output', target: 'mlp', targetPort: 'hidden' },
    { id: 'attention-residual-mlp-residual', source: 'attention-residual', sourcePort: 'output', target: 'mlp-residual', targetPort: 'residual' },
    { id: 'mlp-mlp-residual', source: 'mlp', sourcePort: 'output', target: 'mlp-residual', targetPort: 'branch' },
    { id: 'mlp-residual-final-norm', source: 'mlp-residual', sourcePort: 'output', target: 'final-norm', targetPort: 'hidden' },
    { id: 'final-norm-head', source: 'final-norm', sourcePort: 'output', target: 'head', targetPort: 'hidden' },
  ],
}

export const trBasicPreset: ArchitectureGraph = {
  id: 'tr-basic-residual-mlp',
  name: 'TR Basic · Shared + Residual Top-2',
  architecture: 'custom',
  config: { hiddenSize: 384, queryHeads: 8, keyValueHeads: 2, headDim: 48 },
  contracts: { causal: false, preservesGqaAtZeroGate: false, sdpaCompatible: false, contextualValue: true },
  nodes: [
    { id: 'token-ids', kind: 'input', label: 'Token IDs', role: 'token-ids', position: { x: 35, y: 65 } },
    { id: 'hidden-states', kind: 'input', label: 'Contextual hidden state', role: 'hidden', position: { x: 300, y: 65 } },
    { id: 'fixed-router', kind: 'semantic', atomId: 'deterministic-token-routing', label: 'Fixed Token-ID Router', role: 'output', position: { x: 35, y: 195 }, attributes: { vocabSize: 200019, nExperts: 4, topK: 2, layerIndex: 0, primaryWeight: 0.5 } },
    { id: 'shared', kind: 'semantic', atomId: 'shared-expert-bank', label: 'Shared Dense Expert', role: 'hidden', position: { x: 300, y: 195 }, attributes: { nSharedExperts: 1, intermediateSize: 768, activation: 'swiglu' } },
    { id: 'routed', kind: 'semantic', atomId: 'routed-expert-bank', label: '4 × Routed Residual Experts', role: 'hidden', position: { x: 80, y: 350 }, attributes: { nExperts: 4, intermediateSize: 192, activation: 'swiglu', expertParallelSize: 1 } },
    { id: 'merge', kind: 'semantic', atomId: 'branch-gated-merge', label: 'Shared + Routed Merge', role: 'hidden', position: { x: 225, y: 500 }, attributes: { sharedGateInit: 1, routedGateInit: 0.5 } },
  ],
  edges: [
    { id: 'tokens-router', source: 'token-ids', sourcePort: 'tokenIds', target: 'fixed-router', targetPort: 'tokenIds' },
    { id: 'hidden-shared', source: 'hidden-states', sourcePort: 'hidden', target: 'shared', targetPort: 'hidden' },
    { id: 'hidden-routed', source: 'hidden-states', sourcePort: 'hidden', target: 'routed', targetPort: 'hidden' },
    { id: 'router-indices-routed', source: 'fixed-router', sourcePort: 'expertIndices', target: 'routed', targetPort: 'expertIndices' },
    { id: 'router-weights-routed', source: 'fixed-router', sourcePort: 'expertWeights', target: 'routed', targetPort: 'expertWeights' },
    { id: 'shared-merge', source: 'shared', sourcePort: 'output', target: 'merge', targetPort: 'shared' },
    { id: 'routed-merge', source: 'routed', sourcePort: 'output', target: 'merge', targetPort: 'routed' },
  ],
}

export const complexityDeepPreset: ArchitectureGraph = {
  id: 'complexity-deep-300m',
  name: 'TR 300M',
  architecture: 'custom',
  config: { hiddenSize: 1024, queryHeads: 16, keyValueHeads: 4, headDim: 64 },
  contracts: { causal: true, preservesGqaAtZeroGate: true, sdpaCompatible: true, contextualValue: true },
  nodes: [
    { id: 'tokens', kind: 'input', label: 'Token IDs', role: 'token-ids', position: { x: 190, y: 35 } },
    { id: 'embedding', kind: 'semantic', atomId: 'token-embedding', label: 'Tied token embedding', role: 'hidden', position: { x: 190, y: 135 }, attributes: { vocabSize: 32000, hiddenSize: 1024 } },
    { id: 'attention-norm', kind: 'semantic', atomId: 'rms-norm', label: 'Attention RMSNorm', role: 'hidden', position: { x: 190, y: 245 }, attributes: { epsilon: 1e-6 } },
    { id: 'qkv', kind: 'semantic', atomId: 'qkv-projection', label: 'GQA QKV projection', role: 'output', position: { x: 190, y: 355 }, attributes: { bias: false, fused: true } },
    { id: 'head-layout', kind: 'semantic', atomId: 'attention-head-layout', label: '16 Q / 4 KV heads', role: 'output', position: { x: 190, y: 475 }, attributes: { queryHeads: 16, keyValueHeads: 4, headDim: 64 } },
    { id: 'qk-norm', kind: 'semantic', atomId: 'qk-normalization', label: 'QK-Norm', role: 'output', position: { x: 70, y: 595 }, attributes: { epsilon: 1e-6 } },
    { id: 'rope', kind: 'semantic', atomId: 'rope', label: 'RoPE θ=10000', role: 'output', position: { x: 70, y: 705 }, attributes: { base: 10000 } },
    { id: 'kv-expand', kind: 'semantic', atomId: 'gqa-kv-expand', label: 'GQA KV expansion ×4', role: 'output', position: { x: 310, y: 705 } },
    { id: 'sdpa', kind: 'semantic', atomId: 'causal-sdpa', label: 'Causal SDPA / Flash', role: 'attention', position: { x: 190, y: 825 }, attributes: { dropout: 0 } },
    { id: 'merge-heads', kind: 'semantic', atomId: 'merge-attention-heads', label: 'Merge attention heads', role: 'hidden', position: { x: 190, y: 935 } },
    { id: 'attention-output', kind: 'semantic', atomId: 'attention-output-projection', label: 'Attention output projection', role: 'hidden', position: { x: 190, y: 1045 }, attributes: { bias: false } },
    { id: 'attention-residual', kind: 'semantic', atomId: 'residual-add', label: 'Attention residual add', role: 'hidden', position: { x: 190, y: 1155 } },
    { id: 'mlp-norm', kind: 'semantic', atomId: 'rms-norm', label: 'MLP RMSNorm', role: 'hidden', position: { x: 190, y: 1265 }, attributes: { epsilon: 1e-6 } },
    { id: 'fixed-routes', kind: 'semantic', atomId: 'deterministic-token-routing', label: 'Fixed lexical top-2 lookup', role: 'output', position: { x: 10, y: 1385 }, attributes: { vocabSize: 32000, nExperts: 4, topK: 2, layerIndex: 0, primaryWeight: 0.5 } },
    { id: 'shared', kind: 'semantic', atomId: 'shared-expert-bank', label: 'Shared dense SwiGLU', role: 'hidden', position: { x: 330, y: 1385 }, attributes: { nSharedExperts: 1, intermediateSize: 3840, activation: 'swiglu' } },
    { id: 'routed', kind: 'semantic', atomId: 'routed-expert-bank', label: '4 × routed SwiGLU', role: 'hidden', position: { x: 70, y: 1515 }, attributes: { nExperts: 4, intermediateSize: 64, activation: 'swiglu', expertParallelSize: 1 } },
    { id: 'branch-gates', kind: 'semantic', atomId: 'branch-gated-merge', label: 'Shared + routed gates', role: 'hidden', position: { x: 210, y: 1645 }, attributes: { sharedGateInit: 1, routedGateInit: 0.1 } },
    { id: 'block-residual', kind: 'semantic', atomId: 'residual-add', label: 'MLP residual add', role: 'hidden', position: { x: 210, y: 1765 } },
    { id: 'final-norm', kind: 'semantic', atomId: 'rms-norm', label: 'Final RMSNorm', role: 'hidden', position: { x: 210, y: 1875 }, attributes: { epsilon: 1e-6 } },
    { id: 'head', kind: 'semantic', atomId: 'lm-head', label: 'Tied language-model head', role: 'output', position: { x: 210, y: 1985 }, attributes: { vocabSize: 32000, tieEmbeddingWeights: true, bias: false } },
  ],
  edges: [
    { id: 'tokens-embedding', source: 'tokens', sourcePort: 'tokenIds', target: 'embedding', targetPort: 'tokenIds' },
    { id: 'embedding-attention-norm', source: 'embedding', sourcePort: 'output', target: 'attention-norm', targetPort: 'hidden' },
    { id: 'attention-norm-qkv', source: 'attention-norm', sourcePort: 'output', target: 'qkv', targetPort: 'hidden' },
    { id: 'qkv-q-layout', source: 'qkv', sourcePort: 'q', target: 'head-layout', targetPort: 'q' },
    { id: 'qkv-k-layout', source: 'qkv', sourcePort: 'k', target: 'head-layout', targetPort: 'k' },
    { id: 'qkv-v-layout', source: 'qkv', sourcePort: 'v', target: 'head-layout', targetPort: 'v' },
    { id: 'layout-q-qk-norm', source: 'head-layout', sourcePort: 'qHeads', target: 'qk-norm', targetPort: 'q' },
    { id: 'layout-k-qk-norm', source: 'head-layout', sourcePort: 'kHeads', target: 'qk-norm', targetPort: 'k' },
    { id: 'qk-norm-q-rope', source: 'qk-norm', sourcePort: 'q', target: 'rope', targetPort: 'q' },
    { id: 'qk-norm-k-rope', source: 'qk-norm', sourcePort: 'k', target: 'rope', targetPort: 'k' },
    { id: 'rope-q-sdpa', source: 'rope', sourcePort: 'q', target: 'sdpa', targetPort: 'q' },
    { id: 'rope-k-expand', source: 'rope', sourcePort: 'k', target: 'kv-expand', targetPort: 'k' },
    { id: 'layout-v-expand', source: 'head-layout', sourcePort: 'vHeads', target: 'kv-expand', targetPort: 'v' },
    { id: 'expand-k-sdpa', source: 'kv-expand', sourcePort: 'k', target: 'sdpa', targetPort: 'k' },
    { id: 'expand-v-sdpa', source: 'kv-expand', sourcePort: 'v', target: 'sdpa', targetPort: 'v' },
    { id: 'sdpa-merge-heads', source: 'sdpa', sourcePort: 'output', target: 'merge-heads', targetPort: 'attention' },
    { id: 'merge-heads-output', source: 'merge-heads', sourcePort: 'output', target: 'attention-output', targetPort: 'hidden' },
    { id: 'embedding-attention-residual', source: 'embedding', sourcePort: 'output', target: 'attention-residual', targetPort: 'residual' },
    { id: 'attention-output-residual', source: 'attention-output', sourcePort: 'output', target: 'attention-residual', targetPort: 'branch' },
    { id: 'attention-residual-mlp-norm', source: 'attention-residual', sourcePort: 'output', target: 'mlp-norm', targetPort: 'hidden' },
    { id: 'tokens-fixed-routes', source: 'tokens', sourcePort: 'tokenIds', target: 'fixed-routes', targetPort: 'tokenIds' },
    { id: 'mlp-norm-shared', source: 'mlp-norm', sourcePort: 'output', target: 'shared', targetPort: 'hidden' },
    { id: 'mlp-norm-routed', source: 'mlp-norm', sourcePort: 'output', target: 'routed', targetPort: 'hidden' },
    { id: 'routes-indices-routed', source: 'fixed-routes', sourcePort: 'expertIndices', target: 'routed', targetPort: 'expertIndices' },
    { id: 'routes-weights-routed', source: 'fixed-routes', sourcePort: 'expertWeights', target: 'routed', targetPort: 'expertWeights' },
    { id: 'shared-branch-gates', source: 'shared', sourcePort: 'output', target: 'branch-gates', targetPort: 'shared' },
    { id: 'routed-branch-gates', source: 'routed', sourcePort: 'output', target: 'branch-gates', targetPort: 'routed' },
    { id: 'attention-residual-block-residual', source: 'attention-residual', sourcePort: 'output', target: 'block-residual', targetPort: 'residual' },
    { id: 'branch-gates-block-residual', source: 'branch-gates', sourcePort: 'output', target: 'block-residual', targetPort: 'branch' },
    { id: 'block-residual-final-norm', source: 'block-residual', sourcePort: 'output', target: 'final-norm', targetPort: 'hidden' },
    { id: 'final-norm-head', source: 'final-norm', sourcePort: 'output', target: 'head', targetPort: 'hidden' },
  ],
}

export const tokenMoePreset: ArchitectureGraph = {
  id: 'token-moe',
  name: 'Token Embedding + Routed/Shared Experts',
  architecture: 'custom',
  config: { hiddenSize: 384, queryHeads: 8, keyValueHeads: 2, headDim: 48 },
  contracts: { causal: false, preservesGqaAtZeroGate: false, sdpaCompatible: false, contextualValue: true },
  nodes: [
    { id: 'tokens', kind: 'input', label: 'Token IDs', role: 'token-ids', position: { x: 170, y: 55 } },
    { id: 'embedding', kind: 'semantic', atomId: 'token-embedding', label: 'Token embedding', role: 'hidden', position: { x: 170, y: 155 }, attributes: { vocabSize: 32768, hiddenSize: 384 } },
    { id: 'norm', kind: 'semantic', atomId: 'rms-norm', label: 'RMSNorm', role: 'hidden', position: { x: 170, y: 255 }, attributes: { epsilon: 1e-6 } },
    { id: 'router', kind: 'semantic', atomId: 'moe-router', label: 'Learned Hidden-State Router', role: 'output', position: { x: 45, y: 370 }, attributes: { nExperts: 8, scoringFunction: 'softmax', routerBias: true, routerDtype: 'float32' } },
    { id: 'topk', kind: 'semantic', atomId: 'top-k-routing', label: 'Top-K Routing', role: 'output', position: { x: 45, y: 485 }, attributes: { topK: 2, selectionMethod: 'group-limited-greedy', nExpertGroups: 2, topkGroups: 1, normalizeWeights: true, routedScalingFactor: 1 } },
    { id: 'routed', kind: 'semantic', atomId: 'routed-expert-bank', label: 'Routed Expert Bank', role: 'hidden', position: { x: 45, y: 610 }, attributes: { nExperts: 8, intermediateSize: 1024, activation: 'swiglu', expertParallelSize: 1 } },
    { id: 'shared', kind: 'semantic', atomId: 'shared-expert-bank', label: 'Shared Expert Bank', role: 'hidden', position: { x: 300, y: 485 }, attributes: { nSharedExperts: 2, intermediateSize: 1024, activation: 'swiglu' } },
    { id: 'merge', kind: 'semantic', atomId: 'expert-merge', label: 'Expert Merge', role: 'hidden', position: { x: 170, y: 730 }, attributes: { merge: 'sum' } },
    { id: 'head', kind: 'semantic', atomId: 'lm-head', label: 'Language-model head', role: 'output', position: { x: 170, y: 840 }, attributes: { vocabSize: 32768, tieEmbeddingWeights: false, bias: false } },
  ],
  edges: [
    { id: 'tokens-embedding', source: 'tokens', sourcePort: 'tokenIds', target: 'embedding', targetPort: 'tokenIds' },
    { id: 'embedding-norm', source: 'embedding', sourcePort: 'output', target: 'norm', targetPort: 'hidden' },
    { id: 'norm-router', source: 'norm', sourcePort: 'output', target: 'router', targetPort: 'hidden' },
    { id: 'router-topk', source: 'router', sourcePort: 'scores', target: 'topk', targetPort: 'scores' },
    { id: 'norm-routed', source: 'norm', sourcePort: 'output', target: 'routed', targetPort: 'hidden' },
    { id: 'topk-indices', source: 'topk', sourcePort: 'expertIndices', target: 'routed', targetPort: 'expertIndices' },
    { id: 'topk-weights', source: 'topk', sourcePort: 'expertWeights', target: 'routed', targetPort: 'expertWeights' },
    { id: 'norm-shared', source: 'norm', sourcePort: 'output', target: 'shared', targetPort: 'hidden' },
    { id: 'routed-merge', source: 'routed', sourcePort: 'output', target: 'merge', targetPort: 'routed' },
    { id: 'shared-merge', source: 'shared', sourcePort: 'output', target: 'merge', targetPort: 'shared' },
    { id: 'merge-head', source: 'merge', sourcePort: 'output', target: 'head', targetPort: 'hidden' },
  ],
}

export const gqaPreset: ArchitectureGraph = {
  id: 'gqa-baseline',
  name: 'Grouped Query Attention',
  architecture: 'gqa',
  config: {
    hiddenSize: 384,
    queryHeads: 8,
    keyValueHeads: 2,
    headDim: 48,
  },
  contracts: {
    causal: true,
    preservesGqaAtZeroGate: true,
    sdpaCompatible: true,
    contextualValue: true,
  },
  nodes: [
    { id: 'hidden', kind: 'input', label: 'Hidden state', role: 'hidden', position: { x: 145, y: 55 } },
    { id: 'q-proj', kind: 'linear', label: 'Q projection', role: 'query', position: { x: 20, y: 180 }, attributes: { inFeatures: 384, outFeatures: 384, bias: false } },
    { id: 'k-proj', kind: 'linear', label: 'K projection', role: 'key', position: { x: 145, y: 180 }, attributes: { inFeatures: 384, outFeatures: 96, bias: false } },
    { id: 'v-proj', kind: 'linear', label: 'V projection', role: 'value', position: { x: 270, y: 180 }, attributes: { inFeatures: 384, outFeatures: 96, bias: false } },
    { id: 'sdpa', kind: 'sdpa', label: 'Causal SDPA', role: 'attention', position: { x: 145, y: 310 } },
    { id: 'output', kind: 'linear', label: 'Context output', role: 'output', position: { x: 145, y: 430 }, attributes: { inFeatures: 384, outFeatures: 384, bias: false } },
  ],
  groups: [
    {
      id: 'qkv-projections',
      kind: 'qkv-projection',
      label: 'QKV projection',
      nodeIds: ['q-proj', 'k-proj', 'v-proj'],
      expanded: false,
      position: { x: 40, y: 125 },
    },
  ],
  edges: [
    { id: 'hidden-q', source: 'hidden', target: 'q-proj', label: 'H' },
    { id: 'hidden-k', source: 'hidden', target: 'k-proj', label: 'H' },
    { id: 'hidden-v', source: 'hidden', target: 'v-proj', label: 'H' },
    { id: 'q-sdpa', source: 'q-proj', target: 'sdpa', label: 'Q' },
    { id: 'k-sdpa', source: 'k-proj', target: 'sdpa', label: 'K' },
    { id: 'v-sdpa', source: 'v-proj', target: 'sdpa', label: 'V' },
    { id: 'sdpa-output', source: 'sdpa', target: 'output' },
  ],
}
